MVCCoreLoginRegister/MVCCoreLoginRegister/Controllers/DataArchiveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCCoreLoginRegister.Data;

namespace MVCCoreLoginRegister.Controllers
{
    public class DataArchiveController : Controller
    {
        JobBagContext _context = new JobBagContext();
        // GET: DataArchiveController
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetLot()
        {
            var Lots = _context.TblLot.ToList();
            if (Lots != null)
            {
                return Json(Lots);
            }
            return Json("Failed");
        }
        [HttpPost]
        public IActionResult GetDataArchiveQuery()
        {
            var Lots = _context.TblDataArchiveQuery.ToList();
            if (Lots != null)
            {
                return Json(Lots);
            }
            return Json("Failed");
        }
        [HttpPost]
        public IActionResult QryLot(int LotID)
        {
            var em = _context.QryLot.SingleOrDefault(em => em.LotId == LotID);
            if (em != null)
            {
                return Json(em);
            }
            return Json("Failed");
        }
        [HttpPost]
        public IActionResult DataQuery(int Query, string Lot)
        {
            switch (Query)
            {
                case 1:
                    return QryLineClearance(Lot);
                case 2:
                    return QryAuthorisation(Lot);
                case 3:
                    return QryProductCheckPoint(Lot);
                case 4:
                    return QryMaterial(Lot);
                case 5:
                    return QryQuality(Lot);
                case 6:
                    return QryCavitation(Lot);
                case 7:
                    return QryMachine(Lot);
                case 8:
                    return QryFunctional(Lot);
                default:
                    break;
            }
            return Json("Failed");
        }
        public IActionResult QryLineClearance(string Lot)
        {
            var ems = _context.QryLineClearanceRecords.Where(e => e.LotName == Lot);
            if (ems != null)
            {
                return Json(ems);
            }
            return Json("Failed");
        }
        public IActionResult QryAuthorisation(string Lot)
        {
            var ems = _context.QryAuthorisationToRunRecords.Where(e => e.LotName == Lot);
            if (ems != null)
            {
                return Json(ems);
            }
            return Json("Failed");
        }

        public IActionResult QryProductCheckPoint(string Lot)
        {
            var ems = _context.QryProductCheckPointData.Where(e => e.LotName == Lot);
            if (ems != null)
            {
                return Json(ems);
            }
            return Json("Failed");
        }

        public IActionResult QryMaterial(string Lot)
        {
            var ems = _context.QryMaterialTraceabilityData.Where(e => e.LotName == Lot);
            if (ems != null)
            {
                return Json(ems);
            }
            return Json("Failed");
        }

        public IActionResult QryQuality(string Lot)
        {
            var ems = _context.QryQualityRecords.Where(e => e.LotName == Lot);
            if (ems != null)
            {
                return Json(ems);
            }
            return Json("Failed");
        }

        public IActionResult QryCavitation(string Lot)
        {
            var ems = _context.QryActiveCavitationRecords.Where(e => e.LotName == Lot);
            if (ems != null)
            {
                return Json(ems);
            }
            return Json("Failed");
        }

        public IActionResult QryMachine(string Lot)
        {
            var ems = _context.QryMachineDowntimeRecords.Where(e => e.LotName == Lot);
            if (ems != null)
            {
                return Json(ems);
            }
            return Json("Failed");
        }

        public IActionResult QryFunctional(string Lot)
        {
            var ems = _context.QryFunctionalTestRecords.Where(e=>e.LotName == Lot);
            if (ems != null)
            {
                return Json(ems);
            }
            return Json("Failed");
        }
    }
}

MVCCoreLoginRegister/MVCCoreLoginRegister/Controllers/ProductSetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCCoreLoginRegister.Data;

namespace MVCCoreLoginRegister.Controllers
{
    public class ProductSetupController : Controller
    {
        JobBagContext _context = new JobBagContext();
        // GET: ProductSetup
        public ActionResult LineClearance()
        {
            return View();
        }
        public ActionResult Authorisation()
        {
            return View();
        }
        public ActionResult MaterialLot()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LineClearance(string Lot)
        {
            var lines = _context.TblLineClearance.Where(em => em.LotName == Lot);
            //var lines = _context.TblLineClearance.ToList();
            if (lines != null)
            {
                return Json(lines);
            }
            return Json("Failed");
        }
        [HttpPost]
        public ActionResult SaveLineClearance(string LCTimeStamp, string TechRFID, string TechUsername, string QCRFID, string QCUsername, string LotName)
        {
            try
            {
                var line = new TblLineClearance();
                line.CurrentDate = DateTime.Now;
                line.LctimeStamp = Convert.ToDateTime(LCTimeStamp);
                line.TechRfid = TechRFID;
                line.TechUsername = TechUsername;
                line.Qcrfid = QCRFID;
                line.Qcusername = QCUsername;
                line.LotName = LotName;
                line.LogFile = true;
                _context.TblLineClearance.Add(line);
                _context.SaveChanges();
                return Json("Success to save");
            }
            catch (Exception)
            {
                return Json("Failed");
            }
        }
        [HttpPost]
        public ActionResult AuthorisationToRun(string Lot)
        {
            var lines = _context.TblAuthorisationToRun.Where(em => em.LotName == Lot);
            //var lines = _context.TblAuthorisationToRun.ToList();
            if (lines != null)
            {
                return Json(lines);
            }
            return Json("Failed");
        }
        [HttpPost]
        public ActionResult SaveAuthorisationToRun(string LCTimeStamp, string TechRFID, string TechUsername, string QCRFID, string QCUsername, string LotName)
        {
            try
            {
                var em = new TblAuthorisationToRun();
                em.CurrentDate = DateTime.Now;
                em.AtrtimeStamp = Convert.ToDateTime(LCTimeStamp);
                em.TechRfid = TechRFID;
                em.TechUsername = TechUsername;
                em.Qcrfid = QCRFID;
                em.Qcusername = QCUsername;
                em.LotName = LotName;
                em.LogFile = true;
                _context.TblAuthorisationToRun.Add(em);
                _context.SaveChanges();
                return Json("Success to save");
            }
            catch (Exception)
            {
                return Json("Failed");
            }
        }
        [HttpPost]
        public ActionResult MaterialLot(string Lot)
        {
            var lines = _context.TblMaterialLotControl.Where(em => em.LotName == Lot);
            //var lines = _context.TblMaterialLotControl.ToList();
            if (lines != null)
            {
                return Json(lines);
            }
            return Json("Failed");
        }
        [HttpPost]
        public ActionResult SaveMaterialLot(int CartonNo, string P1lot, string P2lot, string Mblot, string Salot, string Mlctimestamp, string LotName, string Des)
        {
            try
            {
                var em = new TblMaterialLotControl();
                em.CartonNo = CartonNo;
                em.CurrentDate = DateTime.Now;
                em.P1lot = P1lot;
                em.P2lot = P2lot;
                em.Mblot = Mblot;
                em.Salot = Salot;
                em.LotName = LotName;
                em.MlctimeStamp = Convert.ToDateTime(Mlctimestamp);
                em.LotName = LotName;
                em.Des = Des;
                em.LogFile = true;
                _context.TblMaterialLotControl.Add(em);
                _context.SaveChanges();
                return Json("Success to save");
            }
            catch (Exception)
            {
                return Json("Failed");
            }
        }
    }
}

MVCCoreLoginRegister/MVCCoreLoginRegister/Controllers/ProductionControlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCCoreLoginRegister.Data;

namespace MVCCoreLoginRegister.Controllers
{
    public class ProductionControlController : Controller
    {
        JobBagContext _context = new JobBagContext();
        // GET: HomeController1
        public ActionResult ProductCheckpoint()
        {
            return View();
        }
        public ActionResult FunctionalTest()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ProductCheckPoint(string Lot)
        {
            var lines = _context.TblProductCheckPoint.Where(em => em.LotName == Lot);
            //var lines = _context.TblProductCheckPoint.ToList();
            if (lines != null)
            {
                return Json(lines);
            }
            return Json("Failed");
        }
        [HttpPost]
        public ActionResult SaveProductCheckPoint(int CartonNo, string Des, string Product, string CheckPoint, bool McRunning, int ActiveCavities,
            string LotName, decimal ShotWeight, int CycleCount, bool Rejects, string PcptimeStamp)
        {
            try
            {
                var em = new TblProductCheckPoint();
                em.CartonNo = CartonNo;
                em.CurrentDate = DateTime.Now;
                em.Des = Des;
                em.ProductName = Product;
                em.CheckPoint = TimeSpan.Parse(CheckPoint);
                em.McRunning = McRunning;
                em.ActiveCavities = ActiveCavities;
                em.ShotWeight = ShotWeight;
                em.CycleCount = CycleCount;
                em.Rejects = Rejects;
                em.LotName = LotName;
                em.PcptimeStamp = Convert.ToDateTime(PcptimeStamp);
                em.LogFile = true;

                _context.TblProductCheckPoint.Add(em);
                _context.SaveChanges();
                return Json("Success to save");
            }
            catch (Exception)
            {
                return Json("Failed");
            }
        }
        [HttpPost]
        public ActionResult FunctionalTest(string Lot)
        {
            var lines = _context.TblFunctionalTest.Where(em => em.LotName == Lot);
            //var lines = _context.TblFunctionalTest.ToList();
            if (lines != null)
            {
                return Json(lines);
            }
            return Json("Failed");
        }
        [HttpPost]
        public ActionResult FunctionalTestType()
        {
            var lines = _context.TblFunctionalTestType.ToList();
            if (lines != null)
            {
                return Json(lines);
            }
            return Json("Failed");
        }
        [HttpPost]
        public ActionResult FunctionalTestResult()
        {

            var lines = _context.TblFunctionalTestResult.ToList();
            if (lines != null)
            {
                return Json(lines);
            }
            return Json("Failed");
        }
        [HttpPost]
        public ActionResult SaveFunctionalTest(int CartonNo, string Comment, string Des, string FttimeStamp,
            string LotName, string Product, string Result, int SampleSize, string TestType)
        {
            try
            {
                var em = new TblFunctionalTest();
                em.CartonNo = CartonNo;
                em.Comment = Comment;
                em.CurrentDate = DateTime.Now;
                em.Des = Des;
                em.FttimeStamp = Convert.ToDateTime(FttimeStamp);
                em.LotName = LotName;
                em.ProductName = Product;
                em.Result = Result;
                em.SampleSize = SampleSize;
                em.TestType = TestType;
                em.LogFile = true;
                _context.TblFunctionalTest.Add(em);
                _context.SaveChanges();
                return Json("Success to save");
            }
            catch (Exception)
            {
                return Json("Failed");
            }
        }
    }
}

MVCCoreLoginRegister/MVCCoreLoginRegister/Controllers/SupportingDocController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using MVCCoreLoginRegister.Data;

namespace MVCCoreLoginRegister.Controllers
{
    public class SupportingDocController : Controller
    {
        JobBagContext _context = new JobBagContext();
        // GET: SupportingDocController
        public ActionResult ProductDrawing()
        {
            return View();
        }
        public ActionResult ProductQISheet()
        {
            return View();
        }
        public ActionResult PackingSpec()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ProductDrawing(string Product)
        {
            var em = _context.TblProduct.SingleOrDefault(em => em.ProductName == Product);
            if (em!=null)
            {
                return Json(em);
            }
            return Json("Failed");
        }
    }
}

MVCCoreLoginRegister/MVCCoreLoginRegister/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCCoreLoginRegister</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCCoreLoginRegister</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav text-right float-right">
                        @if (Context.Request.Cookies["Username"] != null)
                        {
                            <li class="nav-item">
                                <a id="manage" class="nav-link text-dark" asp-page="/Account/Login" title="Manage">Hello @(Context.Request.Cookies["Username"])!</a>
                            </li>
                            <li class="nav-item">
                                <form id="logoutForm" class="form-inline" asp-area="" asp-controller="Account" asp-action="Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                    <button id="logout" type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Password">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                    @if (Context.Request.Cookies["Username"] != null)
                    {
                        <ul class="navbar-nav flex-grow-1">

                            <li class="dropdown">
                                <a href="#" class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Production Setup <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a class="nav-link text-danger" asp-area="" asp-controller="ProductSetup" asp-action="LineClearance">Line Clearance</a></li>
                                    <li><a class="nav-link text-danger" asp-area="" asp-controller="ProductSetup" asp-action="Authorisation">Authorisation To Run</a></li>
                                    <li><a class="nav-link text-danger" asp-area="" asp-controller="ProductSetup" asp-action="MaterialLot">Material Lot Control</a></li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="#" class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Production Control<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a class="nav-link text-danger" asp-area="" asp-controller="ProductionControl" asp-action="ProductCheckpoint">Product Checkpoint</a></li>
                                    <li><a class="nav-link text-danger" asp-area="" asp-controller="ProductionControl" asp-action="functionalTest">Functional Test</a></li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="#" class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Supporting Documentation<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a class="nav-link text-danger" asp-area="" asp-controller="SupportingDoc" asp-action="ProductDrawing">Product Drawing</a></li>
                                    <li><a class="nav-link text-danger" asp-area="" asp-controller="SupportingDoc" asp-action="ProductQISheet">Product Quality Information Sheet</a></li>
                                    <li><a class="nav-link text-danger" asp-area="" asp-controller="SupportingDoc" asp-action="PackingSpec">Packing Specification</a></li>
                                </ul>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="DataArchive" asp-action="Index">Data Archive</a>
                            </li>
                        </ul>
                    }

                </div>

            </div>
        </nav>
    </header>
    <div style="margin:40px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <h5>&copy; Name</h5>
                </div>
                <div class="col-sm-8">
                </div>
                <div class="col-sm-2">
                    <h5 id="timeout">Exiting Page in </h5>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/toastr.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>